-- Empleados de ejemplo
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (1, 'MARIA FERNANDA LOPEZ GARCIA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (2, 'CARLOS ANDRES MARTINEZ RUIZ', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (3, 'JUAN PABLO RAMIREZ TORRES', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (4, 'ANDREA CAROLINA SILVA MENDEZ', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (5, 'DIEGO ALEJANDRO CASTRO RIOS', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (6, 'LAURA VALENTINA HERRERA DIAZ', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (7, 'SANTIAGO FELIPE MORALES VEGA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (8, 'CAMILA ANDREA ROJAS PENA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (9, 'NICOLAS ESTEBAN VARGAS LUNA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (10, 'DANIELA PATRICIA ORTIZ CAMPO', 'Integraciones', true);

-- Ausencias de ejemplo
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (1, '2026-02-23', 'C', 'Compensatorio');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (1, '2026-03-13', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-03-17', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-27', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-28', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-29', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-30', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-31', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-03-18', 'VT', 'Vacaciones Tomadas');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-08', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-09', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-10', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (4, '2026-03-02', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (4, '2026-03-24', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (5, '2026-03-13', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (5, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-18', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-19', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-20', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-06', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-16', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-17', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-18', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-02-16', 'C', 'Compensatorio');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-03-30', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-04-01', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (9, '2026-02-09', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (9, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (10, '2026-03-26', 'F', 'Flex');
