-- Empleados del área de Integraciones
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (1, 'SANDRA MAYERLY CRUZ PENAGOS', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (2, 'CRISTIAN FELIPE ECHEVERRIA LEON', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (3, 'GERONIMO ALEJANDRO VELASCO HERNANDEZ', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (4, 'ALEXANDER ARCE MUNOZ', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (5, 'ALEXANDER PEREZ ECUA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (6, 'BEATRIZ ELENA ROBLES CIRO', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (7, 'CRISTIAN YOVHER SOLARTE TORRES', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (8, 'LUIS ALBERTO FORERO GUZMAN', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (9, 'SANDRA PATRICIA LARA FIGUEROA', 'Integraciones', true);
INSERT IGNORE INTO employees (id, full_name, area, active) VALUES (10, 'WILMER ANDRES GOMEZ MORENO', 'Integraciones', true);

-- Ausencias 2026 (extraídas del Excel)
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (1, '2026-02-23', 'C', 'Compensatorio');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (1, '2026-03-13', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-03-17', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-27', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-28', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-29', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-30', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-07-31', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-08-03', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-08-04', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-08-05', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (2, '2026-08-06', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-03-18', 'VT', 'Vacaciones Tomadas');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-08', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-09', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-10', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-13', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-14', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-15', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-16', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-17', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-20', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-21', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-22', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-23', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-24', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-27', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-28', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-29', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (3, '2026-04-30', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (4, '2026-03-02', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (4, '2026-03-24', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (4, '2026-03-25', 'VT', 'Vacaciones Tomadas');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (5, '2026-03-13', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (5, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (5, '2026-04-01', 'VT', 'Vacaciones Tomadas');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-03-31', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-04-10', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-18', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-19', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-20', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-21', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-24', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-26', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-27', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-28', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-08-31', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-09-01', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-09-02', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-09-03', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-09-04', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (6, '2026-09-07', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-06', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-16', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-17', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-18', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-19', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-20', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-23', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-24', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-26', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-02-27', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (7, '2026-03-27', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-02-16', 'C', 'Compensatorio');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-03-30', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-03-31', 'VT', 'Vacaciones Tomadas');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-04-01', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-04-06', 'V', 'Vacaciones');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (8, '2026-04-09', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (9, '2026-02-09', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (9, '2026-03-20', 'F', 'Flex');
INSERT IGNORE INTO absences (employee_id, date, type, notes) VALUES (10, '2026-03-26', 'F', 'Flex');
